# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
